spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e-com
    username: root
    password:
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  ecom:
    app:
      jwt-secret: abcdefghijklmnopqrstuvwxyzabsbchdchdcvdgshcvgdshvcdsvdbcvjhbv
      jwt-expiration: 3600000
      jwt-cookieName : ecom-cookie
logging:
  level:
    com.ecommerce: debug
project:
  image: images/